from django.views.generic import TemplateView
from django.shortcuts import render

# class page_0(TemplateView): template_name = 'pages/page_0.html'
def page_0(request): return render(request, 'pages/page_0.html', {'name': 'Home' })

def project_0(request): return render(request, 'pages/page_0.html', {'name': 'Project 0' })
def project_1(request): return render(request, 'pages/page_0.html', {'name': 'Project 1' })
def project_2(request): return render(request, 'pages/page_0.html', {'name': 'Project 2' })
def project_3(request): return render(request, 'pages/page_0.html', {'name': 'Project 3' })
def project_4(request): return render(request, 'pages/page_0.html', {'name': 'Project 4' })
def project_5(request): return render(request, 'pages/page_0.html', {'name': 'Project 5' })
def project_6(request): return render(request, 'pages/page_0.html', {'name': 'Project 6' })
def project_7(request): return render(request, 'pages/page_0.html', {'name': 'Project 7' })
def project_8(request): return render(request, 'pages/page_0.html', {'name': 'Project 8' })
def project_9(request): return render(request, 'pages/page_0.html', {'name': 'Project 9' })

def project_10(request): return render(request, 'pages/page_0.html', {'name': 'Project 10' })
def project_11(request): return render(request, 'pages/page_0.html', {'name': 'Project 11' })
def project_12(request): return render(request, 'pages/page_0.html', {'name': 'Project 12' })
def project_13(request): return render(request, 'pages/page_0.html', {'name': 'Project 13' })
def project_14(request): return render(request, 'pages/page_0.html', {'name': 'Project 14' })
def project_15(request): return render(request, 'pages/page_0.html', {'name': 'Project 15' })
def project_16(request): return render(request, 'pages/page_0.html', {'name': 'Project 16' })
def project_17(request): return render(request, 'pages/page_0.html', {'name': 'Project 17' })
def project_18(request): return render(request, 'pages/page_0.html', {'name': 'Project 18' })
def project_19(request): return render(request, 'pages/page_0.html', {'name': 'Project 19' })

def project_20(request): return render(request, 'pages/page_0.html', {'name': 'Project 20' })
def project_21(request): return render(request, 'pages/page_0.html', {'name': 'Project 21' })
def project_22(request): return render(request, 'pages/page_0.html', {'name': 'Project 22' })
def project_23(request): return render(request, 'pages/page_0.html', {'name': 'Project 23' })
def project_24(request): return render(request, 'pages/page_0.html', {'name': 'Project 24' })
def project_25(request): return render(request, 'pages/page_0.html', {'name': 'Project 25' })
def project_26(request): return render(request, 'pages/page_0.html', {'name': 'Project 26' })
def project_27(request): return render(request, 'pages/page_0.html', {'name': 'Project 27' })
def project_28(request): return render(request, 'pages/page_0.html', {'name': 'Project 28' })
def project_29(request): return render(request, 'pages/page_0.html', {'name': 'Project 29' })

def project_30(request): return render(request, 'pages/page_0.html', {'name': 'Project 30' })
def project_31(request): return render(request, 'pages/page_0.html', {'name': 'Project 31' })
def project_32(request): return render(request, 'pages/page_0.html', {'name': 'Project 32' })
def project_33(request): return render(request, 'pages/page_0.html', {'name': 'Project 33' })
def project_34(request): return render(request, 'pages/page_0.html', {'name': 'Project 34' })
def project_35(request): return render(request, 'pages/page_0.html', {'name': 'Project 35' })
def project_36(request): return render(request, 'pages/page_0.html', {'name': 'Project 36' })
def project_37(request): return render(request, 'pages/page_0.html', {'name': 'Project 37' })
def project_38(request): return render(request, 'pages/page_0.html', {'name': 'Project 38' })
def project_39(request): return render(request, 'pages/page_0.html', {'name': 'Project 39' })

def project_40(request): return render(request, 'pages/page_0.html', {'name': 'Project 40' })
def project_41(request): return render(request, 'pages/page_0.html', {'name': 'Project 41' })
def project_42(request): return render(request, 'pages/page_0.html', {'name': 'Project 42' })
def project_43(request): return render(request, 'pages/page_0.html', {'name': 'Project 43' })
def project_44(request): return render(request, 'pages/page_0.html', {'name': 'Project 44' })
def project_45(request): return render(request, 'pages/page_0.html', {'name': 'Project 45' })
def project_46(request): return render(request, 'pages/page_0.html', {'name': 'Project 46' })
def project_47(request): return render(request, 'pages/page_0.html', {'name': 'Project 47' })
def project_48(request): return render(request, 'pages/page_0.html', {'name': 'Project 48' })
def project_49(request): return render(request, 'pages/page_0.html', {'name': 'Project 49' })

def project_50(request): return render(request, 'pages/page_0.html', {'name': 'Project 50' })
def project_51(request): return render(request, 'pages/page_0.html', {'name': 'Project 51' })
def project_52(request): return render(request, 'pages/page_0.html', {'name': 'Project 52' })
def project_53(request): return render(request, 'pages/page_0.html', {'name': 'Project 53' })
def project_54(request): return render(request, 'pages/page_0.html', {'name': 'Project 54' })
def project_55(request): return render(request, 'pages/page_0.html', {'name': 'Project 55' })
def project_56(request): return render(request, 'pages/page_0.html', {'name': 'Project 56' })
def project_57(request): return render(request, 'pages/page_0.html', {'name': 'Project 57' })
def project_58(request): return render(request, 'pages/page_0.html', {'name': 'Project 58' })
def project_59(request): return render(request, 'pages/page_0.html', {'name': 'Project 59' })

def project_60(request): return render(request, 'pages/page_0.html', {'name': 'Project 60' })
def project_61(request): return render(request, 'pages/page_0.html', {'name': 'Project 61' })
def project_62(request): return render(request, 'pages/page_0.html', {'name': 'Project 62' })
def project_63(request): return render(request, 'pages/page_0.html', {'name': 'Project 63' })
def project_64(request): return render(request, 'pages/page_0.html', {'name': 'Project 64' })
def project_65(request): return render(request, 'pages/page_0.html', {'name': 'Project 65' })
def project_66(request): return render(request, 'pages/page_0.html', {'name': 'Project 66' })
def project_67(request): return render(request, 'pages/page_0.html', {'name': 'Project 67' })
def project_68(request): return render(request, 'pages/page_0.html', {'name': 'Project 68' })
def project_69(request): return render(request, 'pages/page_0.html', {'name': 'Project 69' })

def project_70(request): return render(request, 'pages/page_0.html', {'name': 'Project 70' })
def project_71(request): return render(request, 'pages/page_0.html', {'name': 'Project 71' })
def project_72(request): return render(request, 'pages/page_0.html', {'name': 'Project 72' })
def project_73(request): return render(request, 'pages/page_0.html', {'name': 'Project 73' })
def project_74(request): return render(request, 'pages/page_0.html', {'name': 'Project 74' })
def project_75(request): return render(request, 'pages/page_0.html', {'name': 'Project 75' })
def project_76(request): return render(request, 'pages/page_0.html', {'name': 'Project 76' })
def project_77(request): return render(request, 'pages/page_0.html', {'name': 'Project 77' })
def project_78(request): return render(request, 'pages/page_0.html', {'name': 'Project 78' })
def project_79(request): return render(request, 'pages/page_0.html', {'name': 'Project 79' })

def project_80(request): return render(request, 'pages/page_0.html', {'name': 'Project 80' })
def project_81(request): return render(request, 'pages/page_0.html', {'name': 'Project 81' })
def project_82(request): return render(request, 'pages/page_0.html', {'name': 'Project 82' })
def project_83(request): return render(request, 'pages/page_0.html', {'name': 'Project 83' })
def project_84(request): return render(request, 'pages/page_0.html', {'name': 'Project 84' })
def project_85(request): return render(request, 'pages/page_0.html', {'name': 'Project 85' })
def project_86(request): return render(request, 'pages/page_0.html', {'name': 'Project 86' })
def project_87(request): return render(request, 'pages/page_0.html', {'name': 'Project 87' })
def project_88(request): return render(request, 'pages/page_0.html', {'name': 'Project 88' })
def project_89(request): return render(request, 'pages/page_0.html', {'name': 'Project 89' })

def project_90(request): return render(request, 'pages/page_0.html', {'name': 'Project 90' })
def project_91(request): return render(request, 'pages/page_0.html', {'name': 'Project 91' })
def project_92(request): return render(request, 'pages/page_0.html', {'name': 'Project 92' })
def project_93(request): return render(request, 'pages/page_0.html', {'name': 'Project 93' })
def project_94(request): return render(request, 'pages/page_0.html', {'name': 'Project 94' })
def project_95(request): return render(request, 'pages/page_0.html', {'name': 'Project 95' })
def project_96(request): return render(request, 'pages/page_0.html', {'name': 'Project 96' })
def project_97(request): return render(request, 'pages/page_0.html', {'name': 'Project 97' })
def project_98(request): return render(request, 'pages/page_0.html', {'name': 'Project 98' })
def project_99(request): return render(request, 'pages/page_0.html', {'name': 'Project 99' })
