from django.views.generic import TemplateView
from django.shortcuts import render

# class page_2(TemplateView): template_name = 'pages/page_2.html'
def page_2(request): return render(request, 'pages/page_2.html', {'name': 'Page 2' })

def project_200(request): return render(request, 'pages/page_1.html', {'name': 'Project 200' })
def project_201(request): return render(request, 'pages/page_1.html', {'name': 'Project 201' })
def project_202(request): return render(request, 'pages/page_1.html', {'name': 'Project 202' })
def project_203(request): return render(request, 'pages/page_1.html', {'name': 'Project 203' })
def project_204(request): return render(request, 'pages/page_1.html', {'name': 'Project 204' })
def project_205(request): return render(request, 'pages/page_1.html', {'name': 'Project 205' })
def project_206(request): return render(request, 'pages/page_1.html', {'name': 'Project 206' })
def project_207(request): return render(request, 'pages/page_1.html', {'name': 'Project 207' })
def project_208(request): return render(request, 'pages/page_1.html', {'name': 'Project 208' })
def project_209(request): return render(request, 'pages/page_1.html', {'name': 'Project 209' })

def project_210(request): return render(request, 'pages/page_1.html', {'name': 'Project 210' })
def project_211(request): return render(request, 'pages/page_1.html', {'name': 'Project 211' })
def project_212(request): return render(request, 'pages/page_1.html', {'name': 'Project 212' })
def project_213(request): return render(request, 'pages/page_1.html', {'name': 'Project 213' })
def project_214(request): return render(request, 'pages/page_1.html', {'name': 'Project 214' })
def project_215(request): return render(request, 'pages/page_1.html', {'name': 'Project 215' })
def project_216(request): return render(request, 'pages/page_1.html', {'name': 'Project 216' })
def project_217(request): return render(request, 'pages/page_1.html', {'name': 'Project 217' })
def project_218(request): return render(request, 'pages/page_1.html', {'name': 'Project 218' })
def project_219(request): return render(request, 'pages/page_1.html', {'name': 'Project 219' })

def project_220(request): return render(request, 'pages/page_1.html', {'name': 'Project 220' })
def project_221(request): return render(request, 'pages/page_1.html', {'name': 'Project 221' })
def project_222(request): return render(request, 'pages/page_1.html', {'name': 'Project 222' })
def project_223(request): return render(request, 'pages/page_1.html', {'name': 'Project 223' })
def project_224(request): return render(request, 'pages/page_1.html', {'name': 'Project 224' })
def project_225(request): return render(request, 'pages/page_1.html', {'name': 'Project 225' })
def project_226(request): return render(request, 'pages/page_1.html', {'name': 'Project 226' })
def project_227(request): return render(request, 'pages/page_1.html', {'name': 'Project 227' })
def project_228(request): return render(request, 'pages/page_1.html', {'name': 'Project 228' })
def project_229(request): return render(request, 'pages/page_1.html', {'name': 'Project 229' })

def project_230(request): return render(request, 'pages/page_1.html', {'name': 'Project 230' })
def project_231(request): return render(request, 'pages/page_1.html', {'name': 'Project 231' })
def project_232(request): return render(request, 'pages/page_1.html', {'name': 'Project 232' })
def project_233(request): return render(request, 'pages/page_1.html', {'name': 'Project 233' })
def project_234(request): return render(request, 'pages/page_1.html', {'name': 'Project 234' })
def project_235(request): return render(request, 'pages/page_1.html', {'name': 'Project 235' })
def project_236(request): return render(request, 'pages/page_1.html', {'name': 'Project 236' })
def project_237(request): return render(request, 'pages/page_1.html', {'name': 'Project 237' })
def project_238(request): return render(request, 'pages/page_1.html', {'name': 'Project 238' })
def project_239(request): return render(request, 'pages/page_1.html', {'name': 'Project 239' })

def project_240(request): return render(request, 'pages/page_1.html', {'name': 'Project 240' })
def project_241(request): return render(request, 'pages/page_1.html', {'name': 'Project 241' })
def project_242(request): return render(request, 'pages/page_1.html', {'name': 'Project 242' })
def project_243(request): return render(request, 'pages/page_1.html', {'name': 'Project 243' })
def project_244(request): return render(request, 'pages/page_1.html', {'name': 'Project 244' })
def project_245(request): return render(request, 'pages/page_1.html', {'name': 'Project 245' })
def project_246(request): return render(request, 'pages/page_1.html', {'name': 'Project 246' })
def project_247(request): return render(request, 'pages/page_1.html', {'name': 'Project 247' })
def project_248(request): return render(request, 'pages/page_1.html', {'name': 'Project 248' })
def project_249(request): return render(request, 'pages/page_1.html', {'name': 'Project 249' })

def project_250(request): return render(request, 'pages/page_1.html', {'name': 'Project 250' })
def project_251(request): return render(request, 'pages/page_1.html', {'name': 'Project 251' })
def project_252(request): return render(request, 'pages/page_1.html', {'name': 'Project 252' })
def project_253(request): return render(request, 'pages/page_1.html', {'name': 'Project 253' })
def project_254(request): return render(request, 'pages/page_1.html', {'name': 'Project 254' })
def project_255(request): return render(request, 'pages/page_1.html', {'name': 'Project 255' })
def project_256(request): return render(request, 'pages/page_1.html', {'name': 'Project 256' })
def project_257(request): return render(request, 'pages/page_1.html', {'name': 'Project 257' })
def project_258(request): return render(request, 'pages/page_1.html', {'name': 'Project 258' })
def project_259(request): return render(request, 'pages/page_1.html', {'name': 'Project 259' })

def project_260(request): return render(request, 'pages/page_1.html', {'name': 'Project 260' })
def project_261(request): return render(request, 'pages/page_1.html', {'name': 'Project 261' })
def project_262(request): return render(request, 'pages/page_1.html', {'name': 'Project 262' })
def project_263(request): return render(request, 'pages/page_1.html', {'name': 'Project 263' })
def project_264(request): return render(request, 'pages/page_1.html', {'name': 'Project 264' })
def project_265(request): return render(request, 'pages/page_1.html', {'name': 'Project 265' })
def project_266(request): return render(request, 'pages/page_1.html', {'name': 'Project 266' })
def project_267(request): return render(request, 'pages/page_1.html', {'name': 'Project 267' })
def project_268(request): return render(request, 'pages/page_1.html', {'name': 'Project 268' })
def project_269(request): return render(request, 'pages/page_1.html', {'name': 'Project 269' })

def project_270(request): return render(request, 'pages/page_1.html', {'name': 'Project 270' })
def project_271(request): return render(request, 'pages/page_1.html', {'name': 'Project 271' })
def project_272(request): return render(request, 'pages/page_1.html', {'name': 'Project 272' })
def project_273(request): return render(request, 'pages/page_1.html', {'name': 'Project 273' })
def project_274(request): return render(request, 'pages/page_1.html', {'name': 'Project 274' })
def project_275(request): return render(request, 'pages/page_1.html', {'name': 'Project 275' })
def project_276(request): return render(request, 'pages/page_1.html', {'name': 'Project 276' })
def project_277(request): return render(request, 'pages/page_1.html', {'name': 'Project 277' })
def project_278(request): return render(request, 'pages/page_1.html', {'name': 'Project 278' })
def project_279(request): return render(request, 'pages/page_1.html', {'name': 'Project 279' })

def project_280(request): return render(request, 'pages/page_1.html', {'name': 'Project 280' })
def project_281(request): return render(request, 'pages/page_1.html', {'name': 'Project 281' })
def project_282(request): return render(request, 'pages/page_1.html', {'name': 'Project 282' })
def project_283(request): return render(request, 'pages/page_1.html', {'name': 'Project 283' })
def project_284(request): return render(request, 'pages/page_1.html', {'name': 'Project 284' })
def project_285(request): return render(request, 'pages/page_1.html', {'name': 'Project 285' })
def project_286(request): return render(request, 'pages/page_1.html', {'name': 'Project 286' })
def project_287(request): return render(request, 'pages/page_1.html', {'name': 'Project 287' })
def project_288(request): return render(request, 'pages/page_1.html', {'name': 'Project 288' })
def project_289(request): return render(request, 'pages/page_1.html', {'name': 'Project 289' })

def project_290(request): return render(request, 'pages/page_1.html', {'name': 'Project 290' })
def project_291(request): return render(request, 'pages/page_1.html', {'name': 'Project 291' })
def project_292(request): return render(request, 'pages/page_1.html', {'name': 'Project 292' })
def project_293(request): return render(request, 'pages/page_1.html', {'name': 'Project 293' })
def project_294(request): return render(request, 'pages/page_1.html', {'name': 'Project 294' })
def project_295(request): return render(request, 'pages/page_1.html', {'name': 'Project 295' })
def project_296(request): return render(request, 'pages/page_1.html', {'name': 'Project 296' })
def project_297(request): return render(request, 'pages/page_1.html', {'name': 'Project 297' })
def project_298(request): return render(request, 'pages/page_1.html', {'name': 'Project 298' })
def project_299(request): return render(request, 'pages/page_1.html', {'name': 'Project 299' })
