from django.views.generic import TemplateView
from django.shortcuts import render

# class page_1(TemplateView): template_name = 'pages/page_1.html'
def page_1(request): return render(request, 'pages/page_1.html', {'name': 'Page 1' })

def project_100(request): return render(request, 'pages/page_1.html', {'name': 'Project 100' })
def project_101(request): return render(request, 'pages/page_1.html', {'name': 'Project 101' })
def project_102(request): return render(request, 'pages/page_1.html', {'name': 'Project 102' })
def project_103(request): return render(request, 'pages/page_1.html', {'name': 'Project 103' })
def project_104(request): return render(request, 'pages/page_1.html', {'name': 'Project 104' })
def project_105(request): return render(request, 'pages/page_1.html', {'name': 'Project 105' })
def project_106(request): return render(request, 'pages/page_1.html', {'name': 'Project 106' })
def project_107(request): return render(request, 'pages/page_1.html', {'name': 'Project 107' })
def project_108(request): return render(request, 'pages/page_1.html', {'name': 'Project 108' })
def project_109(request): return render(request, 'pages/page_1.html', {'name': 'Project 109' })

def project_110(request): return render(request, 'pages/page_1.html', {'name': 'Project 110' })
def project_111(request): return render(request, 'pages/page_1.html', {'name': 'Project 111' })
def project_112(request): return render(request, 'pages/page_1.html', {'name': 'Project 112' })
def project_113(request): return render(request, 'pages/page_1.html', {'name': 'Project 113' })
def project_114(request): return render(request, 'pages/page_1.html', {'name': 'Project 114' })
def project_115(request): return render(request, 'pages/page_1.html', {'name': 'Project 115' })
def project_116(request): return render(request, 'pages/page_1.html', {'name': 'Project 116' })
def project_117(request): return render(request, 'pages/page_1.html', {'name': 'Project 117' })
def project_118(request): return render(request, 'pages/page_1.html', {'name': 'Project 118' })
def project_119(request): return render(request, 'pages/page_1.html', {'name': 'Project 119' })

def project_120(request): return render(request, 'pages/page_1.html', {'name': 'Project 120' })
def project_121(request): return render(request, 'pages/page_1.html', {'name': 'Project 121' })
def project_122(request): return render(request, 'pages/page_1.html', {'name': 'Project 122' })
def project_123(request): return render(request, 'pages/page_1.html', {'name': 'Project 123' })
def project_124(request): return render(request, 'pages/page_1.html', {'name': 'Project 124' })
def project_125(request): return render(request, 'pages/page_1.html', {'name': 'Project 125' })
def project_126(request): return render(request, 'pages/page_1.html', {'name': 'Project 126' })
def project_127(request): return render(request, 'pages/page_1.html', {'name': 'Project 127' })
def project_128(request): return render(request, 'pages/page_1.html', {'name': 'Project 128' })
def project_129(request): return render(request, 'pages/page_1.html', {'name': 'Project 129' })

def project_130(request): return render(request, 'pages/page_1.html', {'name': 'Project 130' })
def project_131(request): return render(request, 'pages/page_1.html', {'name': 'Project 131' })
def project_132(request): return render(request, 'pages/page_1.html', {'name': 'Project 132' })
def project_133(request): return render(request, 'pages/page_1.html', {'name': 'Project 133' })
def project_134(request): return render(request, 'pages/page_1.html', {'name': 'Project 134' })
def project_135(request): return render(request, 'pages/page_1.html', {'name': 'Project 135' })
def project_136(request): return render(request, 'pages/page_1.html', {'name': 'Project 136' })
def project_137(request): return render(request, 'pages/page_1.html', {'name': 'Project 137' })
def project_138(request): return render(request, 'pages/page_1.html', {'name': 'Project 138' })
def project_139(request): return render(request, 'pages/page_1.html', {'name': 'Project 139' })

def project_140(request): return render(request, 'pages/page_1.html', {'name': 'Project 140' })
def project_141(request): return render(request, 'pages/page_1.html', {'name': 'Project 141' })
def project_142(request): return render(request, 'pages/page_1.html', {'name': 'Project 142' })
def project_143(request): return render(request, 'pages/page_1.html', {'name': 'Project 143' })
def project_144(request): return render(request, 'pages/page_1.html', {'name': 'Project 144' })
def project_145(request): return render(request, 'pages/page_1.html', {'name': 'Project 145' })
def project_146(request): return render(request, 'pages/page_1.html', {'name': 'Project 146' })
def project_147(request): return render(request, 'pages/page_1.html', {'name': 'Project 147' })
def project_148(request): return render(request, 'pages/page_1.html', {'name': 'Project 148' })
def project_149(request): return render(request, 'pages/page_1.html', {'name': 'Project 149' })

def project_150(request): return render(request, 'pages/page_1.html', {'name': 'Project 150' })
def project_151(request): return render(request, 'pages/page_1.html', {'name': 'Project 151' })
def project_152(request): return render(request, 'pages/page_1.html', {'name': 'Project 152' })
def project_153(request): return render(request, 'pages/page_1.html', {'name': 'Project 153' })
def project_154(request): return render(request, 'pages/page_1.html', {'name': 'Project 154' })
def project_155(request): return render(request, 'pages/page_1.html', {'name': 'Project 155' })
def project_156(request): return render(request, 'pages/page_1.html', {'name': 'Project 156' })
def project_157(request): return render(request, 'pages/page_1.html', {'name': 'Project 157' })
def project_158(request): return render(request, 'pages/page_1.html', {'name': 'Project 158' })
def project_159(request): return render(request, 'pages/page_1.html', {'name': 'Project 159' })

def project_160(request): return render(request, 'pages/page_1.html', {'name': 'Project 160' })
def project_161(request): return render(request, 'pages/page_1.html', {'name': 'Project 161' })
def project_162(request): return render(request, 'pages/page_1.html', {'name': 'Project 162' })
def project_163(request): return render(request, 'pages/page_1.html', {'name': 'Project 163' })
def project_164(request): return render(request, 'pages/page_1.html', {'name': 'Project 164' })
def project_165(request): return render(request, 'pages/page_1.html', {'name': 'Project 165' })
def project_166(request): return render(request, 'pages/page_1.html', {'name': 'Project 166' })
def project_167(request): return render(request, 'pages/page_1.html', {'name': 'Project 167' })
def project_168(request): return render(request, 'pages/page_1.html', {'name': 'Project 168' })
def project_169(request): return render(request, 'pages/page_1.html', {'name': 'Project 169' })

def project_170(request): return render(request, 'pages/page_1.html', {'name': 'Project 170' })
def project_171(request): return render(request, 'pages/page_1.html', {'name': 'Project 171' })
def project_172(request): return render(request, 'pages/page_1.html', {'name': 'Project 172' })
def project_173(request): return render(request, 'pages/page_1.html', {'name': 'Project 173' })
def project_174(request): return render(request, 'pages/page_1.html', {'name': 'Project 174' })
def project_175(request): return render(request, 'pages/page_1.html', {'name': 'Project 175' })
def project_176(request): return render(request, 'pages/page_1.html', {'name': 'Project 176' })
def project_177(request): return render(request, 'pages/page_1.html', {'name': 'Project 177' })
def project_178(request): return render(request, 'pages/page_1.html', {'name': 'Project 178' })
def project_179(request): return render(request, 'pages/page_1.html', {'name': 'Project 179' })

def project_180(request): return render(request, 'pages/page_1.html', {'name': 'Project 180' })
def project_181(request): return render(request, 'pages/page_1.html', {'name': 'Project 181' })
def project_182(request): return render(request, 'pages/page_1.html', {'name': 'Project 182' })
def project_183(request): return render(request, 'pages/page_1.html', {'name': 'Project 183' })
def project_184(request): return render(request, 'pages/page_1.html', {'name': 'Project 184' })
def project_185(request): return render(request, 'pages/page_1.html', {'name': 'Project 185' })
def project_186(request): return render(request, 'pages/page_1.html', {'name': 'Project 186' })
def project_187(request): return render(request, 'pages/page_1.html', {'name': 'Project 187' })
def project_188(request): return render(request, 'pages/page_1.html', {'name': 'Project 188' })
def project_189(request): return render(request, 'pages/page_1.html', {'name': 'Project 189' })

def project_190(request): return render(request, 'pages/page_1.html', {'name': 'Project 190' })
def project_191(request): return render(request, 'pages/page_1.html', {'name': 'Project 191' })
def project_192(request): return render(request, 'pages/page_1.html', {'name': 'Project 192' })
def project_193(request): return render(request, 'pages/page_1.html', {'name': 'Project 193' })
def project_194(request): return render(request, 'pages/page_1.html', {'name': 'Project 194' })
def project_195(request): return render(request, 'pages/page_1.html', {'name': 'Project 195' })
def project_196(request): return render(request, 'pages/page_1.html', {'name': 'Project 196' })
def project_197(request): return render(request, 'pages/page_1.html', {'name': 'Project 197' })
def project_198(request): return render(request, 'pages/page_1.html', {'name': 'Project 198' })
def project_199(request): return render(request, 'pages/page_1.html', {'name': 'Project 199' })
