from django.views.generic import TemplateView
from django.shortcuts import render

# class page_6(TemplateView): template_name = 'pages/page_6.html'
def page_6(request): return render(request, 'pages/page_6.html', {'name': 'Page 6' })

def project_600(request): return render(request, 'pages/page_1.html', {'name': 'Project 600' })
def project_601(request): return render(request, 'pages/page_1.html', {'name': 'Project 601' })
def project_602(request): return render(request, 'pages/page_1.html', {'name': 'Project 602' })
def project_603(request): return render(request, 'pages/page_1.html', {'name': 'Project 603' })
def project_604(request): return render(request, 'pages/page_1.html', {'name': 'Project 604' })
def project_605(request): return render(request, 'pages/page_1.html', {'name': 'Project 605' })
def project_606(request): return render(request, 'pages/page_1.html', {'name': 'Project 606' })
def project_607(request): return render(request, 'pages/page_1.html', {'name': 'Project 607' })
def project_608(request): return render(request, 'pages/page_1.html', {'name': 'Project 608' })
def project_609(request): return render(request, 'pages/page_1.html', {'name': 'Project 609' })

def project_610(request): return render(request, 'pages/page_1.html', {'name': 'Project 610' })
def project_611(request): return render(request, 'pages/page_1.html', {'name': 'Project 611' })
def project_612(request): return render(request, 'pages/page_1.html', {'name': 'Project 612' })
def project_613(request): return render(request, 'pages/page_1.html', {'name': 'Project 613' })
def project_614(request): return render(request, 'pages/page_1.html', {'name': 'Project 614' })
def project_615(request): return render(request, 'pages/page_1.html', {'name': 'Project 615' })
def project_616(request): return render(request, 'pages/page_1.html', {'name': 'Project 616' })
def project_617(request): return render(request, 'pages/page_1.html', {'name': 'Project 617' })
def project_618(request): return render(request, 'pages/page_1.html', {'name': 'Project 618' })
def project_619(request): return render(request, 'pages/page_1.html', {'name': 'Project 619' })

def project_620(request): return render(request, 'pages/page_1.html', {'name': 'Project 620' })
def project_621(request): return render(request, 'pages/page_1.html', {'name': 'Project 621' })
def project_622(request): return render(request, 'pages/page_1.html', {'name': 'Project 622' })
def project_623(request): return render(request, 'pages/page_1.html', {'name': 'Project 623' })
def project_624(request): return render(request, 'pages/page_1.html', {'name': 'Project 624' })
def project_625(request): return render(request, 'pages/page_1.html', {'name': 'Project 625' })
def project_626(request): return render(request, 'pages/page_1.html', {'name': 'Project 626' })
def project_627(request): return render(request, 'pages/page_1.html', {'name': 'Project 627' })
def project_628(request): return render(request, 'pages/page_1.html', {'name': 'Project 628' })
def project_629(request): return render(request, 'pages/page_1.html', {'name': 'Project 629' })

def project_630(request): return render(request, 'pages/page_1.html', {'name': 'Project 630' })
def project_631(request): return render(request, 'pages/page_1.html', {'name': 'Project 631' })
def project_632(request): return render(request, 'pages/page_1.html', {'name': 'Project 632' })
def project_633(request): return render(request, 'pages/page_1.html', {'name': 'Project 633' })
def project_634(request): return render(request, 'pages/page_1.html', {'name': 'Project 634' })
def project_635(request): return render(request, 'pages/page_1.html', {'name': 'Project 635' })
def project_636(request): return render(request, 'pages/page_1.html', {'name': 'Project 636' })
def project_637(request): return render(request, 'pages/page_1.html', {'name': 'Project 637' })
def project_638(request): return render(request, 'pages/page_1.html', {'name': 'Project 638' })
def project_639(request): return render(request, 'pages/page_1.html', {'name': 'Project 639' })

def project_640(request): return render(request, 'pages/page_1.html', {'name': 'Project 640' })
def project_641(request): return render(request, 'pages/page_1.html', {'name': 'Project 641' })
def project_642(request): return render(request, 'pages/page_1.html', {'name': 'Project 642' })
def project_643(request): return render(request, 'pages/page_1.html', {'name': 'Project 643' })
def project_644(request): return render(request, 'pages/page_1.html', {'name': 'Project 644' })
def project_645(request): return render(request, 'pages/page_1.html', {'name': 'Project 645' })
def project_646(request): return render(request, 'pages/page_1.html', {'name': 'Project 646' })
def project_647(request): return render(request, 'pages/page_1.html', {'name': 'Project 647' })
def project_648(request): return render(request, 'pages/page_1.html', {'name': 'Project 648' })
def project_649(request): return render(request, 'pages/page_1.html', {'name': 'Project 649' })

def project_650(request): return render(request, 'pages/page_1.html', {'name': 'Project 650' })
def project_651(request): return render(request, 'pages/page_1.html', {'name': 'Project 651' })
def project_652(request): return render(request, 'pages/page_1.html', {'name': 'Project 652' })
def project_653(request): return render(request, 'pages/page_1.html', {'name': 'Project 653' })
def project_654(request): return render(request, 'pages/page_1.html', {'name': 'Project 654' })
def project_655(request): return render(request, 'pages/page_1.html', {'name': 'Project 655' })
def project_656(request): return render(request, 'pages/page_1.html', {'name': 'Project 656' })
# def project_657(request): return render(request, 'pages/page_1.html', {'name': 'Project 657' })
# def project_658(request): return render(request, 'pages/page_1.html', {'name': 'Project 658' })
# def project_659(request): return render(request, 'pages/page_1.html', {'name': 'Project 659' })
# 
# def project_660(request): return render(request, 'pages/page_1.html', {'name': 'Project 660' })
# def project_661(request): return render(request, 'pages/page_1.html', {'name': 'Project 661' })
# def project_662(request): return render(request, 'pages/page_1.html', {'name': 'Project 662' })
# def project_663(request): return render(request, 'pages/page_1.html', {'name': 'Project 663' })
# def project_664(request): return render(request, 'pages/page_1.html', {'name': 'Project 664' })
# def project_665(request): return render(request, 'pages/page_1.html', {'name': 'Project 665' })
# def project_666(request): return render(request, 'pages/page_1.html', {'name': 'Project 666' })
# def project_667(request): return render(request, 'pages/page_1.html', {'name': 'Project 667' })
# def project_668(request): return render(request, 'pages/page_1.html', {'name': 'Project 668' })
# def project_669(request): return render(request, 'pages/page_1.html', {'name': 'Project 669' })
#
# def project_670(request): return render(request, 'pages/page_1.html', {'name': 'Project 670' })
# def project_671(request): return render(request, 'pages/page_1.html', {'name': 'Project 671' })
# def project_672(request): return render(request, 'pages/page_1.html', {'name': 'Project 672' })
# def project_673(request): return render(request, 'pages/page_1.html', {'name': 'Project 673' })
# def project_674(request): return render(request, 'pages/page_1.html', {'name': 'Project 674' })
# def project_675(request): return render(request, 'pages/page_1.html', {'name': 'Project 675' })
# def project_676(request): return render(request, 'pages/page_1.html', {'name': 'Project 676' })
# def project_677(request): return render(request, 'pages/page_1.html', {'name': 'Project 677' })
# def project_678(request): return render(request, 'pages/page_1.html', {'name': 'Project 678' })
# def project_679(request): return render(request, 'pages/page_1.html', {'name': 'Project 679' })
#
# def project_680(request): return render(request, 'pages/page_1.html', {'name': 'Project 680' })
# def project_681(request): return render(request, 'pages/page_1.html', {'name': 'Project 681' })
# def project_682(request): return render(request, 'pages/page_1.html', {'name': 'Project 682' })
# def project_683(request): return render(request, 'pages/page_1.html', {'name': 'Project 683' })
# def project_684(request): return render(request, 'pages/page_1.html', {'name': 'Project 684' })
# def project_685(request): return render(request, 'pages/page_1.html', {'name': 'Project 685' })
# def project_686(request): return render(request, 'pages/page_1.html', {'name': 'Project 686' })
# def project_687(request): return render(request, 'pages/page_1.html', {'name': 'Project 687' })
# def project_688(request): return render(request, 'pages/page_1.html', {'name': 'Project 688' })
# def project_689(request): return render(request, 'pages/page_1.html', {'name': 'Project 689' })
#
# def project_690(request): return render(request, 'pages/page_1.html', {'name': 'Project 690' })
# def project_691(request): return render(request, 'pages/page_1.html', {'name': 'Project 691' })
# def project_692(request): return render(request, 'pages/page_1.html', {'name': 'Project 692' })
# def project_693(request): return render(request, 'pages/page_1.html', {'name': 'Project 693' })
# def project_694(request): return render(request, 'pages/page_1.html', {'name': 'Project 694' })
# def project_695(request): return render(request, 'pages/page_1.html', {'name': 'Project 695' })
# def project_696(request): return render(request, 'pages/page_1.html', {'name': 'Project 696' })
# def project_697(request): return render(request, 'pages/page_1.html', {'name': 'Project 697' })
# def project_698(request): return render(request, 'pages/page_1.html', {'name': 'Project 698' })
# def project_699(request): return render(request, 'pages/page_1.html', {'name': 'Project 699' })
