from django.views.generic import TemplateView
from django.shortcuts import render

# class page_5(TemplateView): template_name = 'pages/page_5.html'
def page_5(request): return render(request, 'pages/page_5.html', {'name': 'Page 5' })

def project_500(request): return render(request, 'pages/page_1.html', {'name': 'Project 500' })
def project_501(request): return render(request, 'pages/page_1.html', {'name': 'Project 501' })
def project_502(request): return render(request, 'pages/page_1.html', {'name': 'Project 502' })
def project_503(request): return render(request, 'pages/page_1.html', {'name': 'Project 503' })
def project_504(request): return render(request, 'pages/page_1.html', {'name': 'Project 504' })
def project_505(request): return render(request, 'pages/page_1.html', {'name': 'Project 505' })
def project_506(request): return render(request, 'pages/page_1.html', {'name': 'Project 506' })
def project_507(request): return render(request, 'pages/page_1.html', {'name': 'Project 507' })
def project_508(request): return render(request, 'pages/page_1.html', {'name': 'Project 508' })
def project_509(request): return render(request, 'pages/page_1.html', {'name': 'Project 509' })

def project_510(request): return render(request, 'pages/page_1.html', {'name': 'Project 510' })
def project_511(request): return render(request, 'pages/page_1.html', {'name': 'Project 511' })
def project_512(request): return render(request, 'pages/page_1.html', {'name': 'Project 512' })
def project_513(request): return render(request, 'pages/page_1.html', {'name': 'Project 513' })
def project_514(request): return render(request, 'pages/page_1.html', {'name': 'Project 514' })
def project_515(request): return render(request, 'pages/page_1.html', {'name': 'Project 515' })
def project_516(request): return render(request, 'pages/page_1.html', {'name': 'Project 516' })
def project_517(request): return render(request, 'pages/page_1.html', {'name': 'Project 517' })
def project_518(request): return render(request, 'pages/page_1.html', {'name': 'Project 518' })
def project_519(request): return render(request, 'pages/page_1.html', {'name': 'Project 519' })

def project_520(request): return render(request, 'pages/page_1.html', {'name': 'Project 520' })
def project_521(request): return render(request, 'pages/page_1.html', {'name': 'Project 521' })
def project_522(request): return render(request, 'pages/page_1.html', {'name': 'Project 522' })
def project_523(request): return render(request, 'pages/page_1.html', {'name': 'Project 523' })
def project_524(request): return render(request, 'pages/page_1.html', {'name': 'Project 524' })
def project_525(request): return render(request, 'pages/page_1.html', {'name': 'Project 525' })
def project_526(request): return render(request, 'pages/page_1.html', {'name': 'Project 526' })
def project_527(request): return render(request, 'pages/page_1.html', {'name': 'Project 527' })
def project_528(request): return render(request, 'pages/page_1.html', {'name': 'Project 528' })
def project_529(request): return render(request, 'pages/page_1.html', {'name': 'Project 529' })

def project_530(request): return render(request, 'pages/page_1.html', {'name': 'Project 530' })
def project_531(request): return render(request, 'pages/page_1.html', {'name': 'Project 531' })
def project_532(request): return render(request, 'pages/page_1.html', {'name': 'Project 532' })
def project_533(request): return render(request, 'pages/page_1.html', {'name': 'Project 533' })
def project_534(request): return render(request, 'pages/page_1.html', {'name': 'Project 534' })
def project_535(request): return render(request, 'pages/page_1.html', {'name': 'Project 535' })
def project_536(request): return render(request, 'pages/page_1.html', {'name': 'Project 536' })
def project_537(request): return render(request, 'pages/page_1.html', {'name': 'Project 537' })
def project_538(request): return render(request, 'pages/page_1.html', {'name': 'Project 538' })
def project_539(request): return render(request, 'pages/page_1.html', {'name': 'Project 539' })

def project_540(request): return render(request, 'pages/page_1.html', {'name': 'Project 540' })
def project_541(request): return render(request, 'pages/page_1.html', {'name': 'Project 541' })
def project_542(request): return render(request, 'pages/page_1.html', {'name': 'Project 542' })
def project_543(request): return render(request, 'pages/page_1.html', {'name': 'Project 543' })
def project_544(request): return render(request, 'pages/page_1.html', {'name': 'Project 544' })
def project_545(request): return render(request, 'pages/page_1.html', {'name': 'Project 545' })
def project_546(request): return render(request, 'pages/page_1.html', {'name': 'Project 546' })
def project_547(request): return render(request, 'pages/page_1.html', {'name': 'Project 547' })
def project_548(request): return render(request, 'pages/page_1.html', {'name': 'Project 548' })
def project_549(request): return render(request, 'pages/page_1.html', {'name': 'Project 549' })

def project_550(request): return render(request, 'pages/page_1.html', {'name': 'Project 550' })
def project_551(request): return render(request, 'pages/page_1.html', {'name': 'Project 551' })
def project_552(request): return render(request, 'pages/page_1.html', {'name': 'Project 552' })
def project_553(request): return render(request, 'pages/page_1.html', {'name': 'Project 553' })
def project_554(request): return render(request, 'pages/page_1.html', {'name': 'Project 554' })
def project_555(request): return render(request, 'pages/page_1.html', {'name': 'Project 555' })
def project_556(request): return render(request, 'pages/page_1.html', {'name': 'Project 556' })
def project_557(request): return render(request, 'pages/page_1.html', {'name': 'Project 557' })
def project_558(request): return render(request, 'pages/page_1.html', {'name': 'Project 558' })
def project_559(request): return render(request, 'pages/page_1.html', {'name': 'Project 559' })

def project_560(request): return render(request, 'pages/page_1.html', {'name': 'Project 560' })
def project_561(request): return render(request, 'pages/page_1.html', {'name': 'Project 561' })
def project_562(request): return render(request, 'pages/page_1.html', {'name': 'Project 562' })
def project_563(request): return render(request, 'pages/page_1.html', {'name': 'Project 563' })
def project_564(request): return render(request, 'pages/page_1.html', {'name': 'Project 564' })
def project_565(request): return render(request, 'pages/page_1.html', {'name': 'Project 565' })
def project_566(request): return render(request, 'pages/page_1.html', {'name': 'Project 566' })
def project_567(request): return render(request, 'pages/page_1.html', {'name': 'Project 567' })
def project_568(request): return render(request, 'pages/page_1.html', {'name': 'Project 568' })
def project_569(request): return render(request, 'pages/page_1.html', {'name': 'Project 569' })

def project_570(request): return render(request, 'pages/page_1.html', {'name': 'Project 570' })
def project_571(request): return render(request, 'pages/page_1.html', {'name': 'Project 571' })
def project_572(request): return render(request, 'pages/page_1.html', {'name': 'Project 572' })
def project_573(request): return render(request, 'pages/page_1.html', {'name': 'Project 573' })
def project_574(request): return render(request, 'pages/page_1.html', {'name': 'Project 574' })
def project_575(request): return render(request, 'pages/page_1.html', {'name': 'Project 575' })
def project_576(request): return render(request, 'pages/page_1.html', {'name': 'Project 576' })
def project_577(request): return render(request, 'pages/page_1.html', {'name': 'Project 577' })
def project_578(request): return render(request, 'pages/page_1.html', {'name': 'Project 578' })
def project_579(request): return render(request, 'pages/page_1.html', {'name': 'Project 579' })

def project_580(request): return render(request, 'pages/page_1.html', {'name': 'Project 580' })
def project_581(request): return render(request, 'pages/page_1.html', {'name': 'Project 581' })
def project_582(request): return render(request, 'pages/page_1.html', {'name': 'Project 582' })
def project_583(request): return render(request, 'pages/page_1.html', {'name': 'Project 583' })
def project_584(request): return render(request, 'pages/page_1.html', {'name': 'Project 584' })
def project_585(request): return render(request, 'pages/page_1.html', {'name': 'Project 585' })
def project_586(request): return render(request, 'pages/page_1.html', {'name': 'Project 586' })
def project_587(request): return render(request, 'pages/page_1.html', {'name': 'Project 587' })
def project_588(request): return render(request, 'pages/page_1.html', {'name': 'Project 588' })
def project_589(request): return render(request, 'pages/page_1.html', {'name': 'Project 589' })

def project_590(request): return render(request, 'pages/page_1.html', {'name': 'Project 590' })
def project_591(request): return render(request, 'pages/page_1.html', {'name': 'Project 591' })
def project_592(request): return render(request, 'pages/page_1.html', {'name': 'Project 592' })
def project_593(request): return render(request, 'pages/page_1.html', {'name': 'Project 593' })
def project_594(request): return render(request, 'pages/page_1.html', {'name': 'Project 594' })
def project_595(request): return render(request, 'pages/page_1.html', {'name': 'Project 595' })
def project_596(request): return render(request, 'pages/page_1.html', {'name': 'Project 596' })
def project_597(request): return render(request, 'pages/page_1.html', {'name': 'Project 597' })
def project_598(request): return render(request, 'pages/page_1.html', {'name': 'Project 598' })
def project_599(request): return render(request, 'pages/page_1.html', {'name': 'Project 599' })
