from django.views.generic import TemplateView
from django.shortcuts import render

# class page_3(TemplateView): template_name = 'pages/page_3.html'
def page_3(request): return render(request, 'pages/page_3.html', {'name': 'Page 3' })

def project_300(request): return render(request, 'pages/page_1.html', {'name': 'Project 300' })
def project_301(request): return render(request, 'pages/page_1.html', {'name': 'Project 301' })
def project_302(request): return render(request, 'pages/page_1.html', {'name': 'Project 302' })
def project_303(request): return render(request, 'pages/page_1.html', {'name': 'Project 303' })
def project_304(request): return render(request, 'pages/page_1.html', {'name': 'Project 304' })
def project_305(request): return render(request, 'pages/page_1.html', {'name': 'Project 305' })
def project_306(request): return render(request, 'pages/page_1.html', {'name': 'Project 306' })
def project_307(request): return render(request, 'pages/page_1.html', {'name': 'Project 307' })
def project_308(request): return render(request, 'pages/page_1.html', {'name': 'Project 308' })
def project_309(request): return render(request, 'pages/page_1.html', {'name': 'Project 309' })

def project_310(request): return render(request, 'pages/page_1.html', {'name': 'Project 310' })
def project_311(request): return render(request, 'pages/page_1.html', {'name': 'Project 311' })
def project_312(request): return render(request, 'pages/page_1.html', {'name': 'Project 312' })
def project_313(request): return render(request, 'pages/page_1.html', {'name': 'Project 313' })
def project_314(request): return render(request, 'pages/page_1.html', {'name': 'Project 314' })
def project_315(request): return render(request, 'pages/page_1.html', {'name': 'Project 315' })
def project_316(request): return render(request, 'pages/page_1.html', {'name': 'Project 316' })
def project_317(request): return render(request, 'pages/page_1.html', {'name': 'Project 317' })
def project_318(request): return render(request, 'pages/page_1.html', {'name': 'Project 318' })
def project_319(request): return render(request, 'pages/page_1.html', {'name': 'Project 319' })

def project_320(request): return render(request, 'pages/page_1.html', {'name': 'Project 320' })
def project_321(request): return render(request, 'pages/page_1.html', {'name': 'Project 321' })
def project_322(request): return render(request, 'pages/page_1.html', {'name': 'Project 322' })
def project_323(request): return render(request, 'pages/page_1.html', {'name': 'Project 323' })
def project_324(request): return render(request, 'pages/page_1.html', {'name': 'Project 324' })
def project_325(request): return render(request, 'pages/page_1.html', {'name': 'Project 325' })
def project_326(request): return render(request, 'pages/page_1.html', {'name': 'Project 326' })
def project_327(request): return render(request, 'pages/page_1.html', {'name': 'Project 327' })
def project_328(request): return render(request, 'pages/page_1.html', {'name': 'Project 328' })
def project_329(request): return render(request, 'pages/page_1.html', {'name': 'Project 329' })

def project_330(request): return render(request, 'pages/page_1.html', {'name': 'Project 330' })
def project_331(request): return render(request, 'pages/page_1.html', {'name': 'Project 331' })
def project_332(request): return render(request, 'pages/page_1.html', {'name': 'Project 332' })
def project_333(request): return render(request, 'pages/page_1.html', {'name': 'Project 333' })
def project_334(request): return render(request, 'pages/page_1.html', {'name': 'Project 334' })
def project_335(request): return render(request, 'pages/page_1.html', {'name': 'Project 335' })
def project_336(request): return render(request, 'pages/page_1.html', {'name': 'Project 336' })
def project_337(request): return render(request, 'pages/page_1.html', {'name': 'Project 337' })
def project_338(request): return render(request, 'pages/page_1.html', {'name': 'Project 338' })
def project_339(request): return render(request, 'pages/page_1.html', {'name': 'Project 339' })

def project_340(request): return render(request, 'pages/page_1.html', {'name': 'Project 340' })
def project_341(request): return render(request, 'pages/page_1.html', {'name': 'Project 341' })
def project_342(request): return render(request, 'pages/page_1.html', {'name': 'Project 342' })
def project_343(request): return render(request, 'pages/page_1.html', {'name': 'Project 343' })
def project_344(request): return render(request, 'pages/page_1.html', {'name': 'Project 344' })
def project_345(request): return render(request, 'pages/page_1.html', {'name': 'Project 345' })
def project_346(request): return render(request, 'pages/page_1.html', {'name': 'Project 346' })
def project_347(request): return render(request, 'pages/page_1.html', {'name': 'Project 347' })
def project_348(request): return render(request, 'pages/page_1.html', {'name': 'Project 348' })
def project_349(request): return render(request, 'pages/page_1.html', {'name': 'Project 349' })

def project_350(request): return render(request, 'pages/page_1.html', {'name': 'Project 350' })
def project_351(request): return render(request, 'pages/page_1.html', {'name': 'Project 351' })
def project_352(request): return render(request, 'pages/page_1.html', {'name': 'Project 352' })
def project_353(request): return render(request, 'pages/page_1.html', {'name': 'Project 353' })
def project_354(request): return render(request, 'pages/page_1.html', {'name': 'Project 354' })
def project_355(request): return render(request, 'pages/page_1.html', {'name': 'Project 355' })
def project_356(request): return render(request, 'pages/page_1.html', {'name': 'Project 356' })
def project_357(request): return render(request, 'pages/page_1.html', {'name': 'Project 357' })
def project_358(request): return render(request, 'pages/page_1.html', {'name': 'Project 358' })
def project_359(request): return render(request, 'pages/page_1.html', {'name': 'Project 359' })

def project_360(request): return render(request, 'pages/page_1.html', {'name': 'Project 360' })
def project_361(request): return render(request, 'pages/page_1.html', {'name': 'Project 361' })
def project_362(request): return render(request, 'pages/page_1.html', {'name': 'Project 362' })
def project_363(request): return render(request, 'pages/page_1.html', {'name': 'Project 363' })
def project_364(request): return render(request, 'pages/page_1.html', {'name': 'Project 364' })
def project_365(request): return render(request, 'pages/page_1.html', {'name': 'Project 365' })
def project_366(request): return render(request, 'pages/page_1.html', {'name': 'Project 366' })
def project_367(request): return render(request, 'pages/page_1.html', {'name': 'Project 367' })
def project_368(request): return render(request, 'pages/page_1.html', {'name': 'Project 368' })
def project_369(request): return render(request, 'pages/page_1.html', {'name': 'Project 369' })

def project_370(request): return render(request, 'pages/page_1.html', {'name': 'Project 370' })
def project_371(request): return render(request, 'pages/page_1.html', {'name': 'Project 371' })
def project_372(request): return render(request, 'pages/page_1.html', {'name': 'Project 372' })
def project_373(request): return render(request, 'pages/page_1.html', {'name': 'Project 373' })
def project_374(request): return render(request, 'pages/page_1.html', {'name': 'Project 374' })
def project_375(request): return render(request, 'pages/page_1.html', {'name': 'Project 375' })
def project_376(request): return render(request, 'pages/page_1.html', {'name': 'Project 376' })
def project_377(request): return render(request, 'pages/page_1.html', {'name': 'Project 377' })
def project_378(request): return render(request, 'pages/page_1.html', {'name': 'Project 378' })
def project_379(request): return render(request, 'pages/page_1.html', {'name': 'Project 379' })

def project_380(request): return render(request, 'pages/page_1.html', {'name': 'Project 380' })
def project_381(request): return render(request, 'pages/page_1.html', {'name': 'Project 381' })
def project_382(request): return render(request, 'pages/page_1.html', {'name': 'Project 382' })
def project_383(request): return render(request, 'pages/page_1.html', {'name': 'Project 383' })
def project_384(request): return render(request, 'pages/page_1.html', {'name': 'Project 384' })
def project_385(request): return render(request, 'pages/page_1.html', {'name': 'Project 385' })
def project_386(request): return render(request, 'pages/page_1.html', {'name': 'Project 386' })
def project_387(request): return render(request, 'pages/page_1.html', {'name': 'Project 387' })
def project_388(request): return render(request, 'pages/page_1.html', {'name': 'Project 388' })
def project_389(request): return render(request, 'pages/page_1.html', {'name': 'Project 389' })

def project_390(request): return render(request, 'pages/page_1.html', {'name': 'Project 390' })
def project_391(request): return render(request, 'pages/page_1.html', {'name': 'Project 391' })
def project_392(request): return render(request, 'pages/page_1.html', {'name': 'Project 392' })
def project_393(request): return render(request, 'pages/page_1.html', {'name': 'Project 393' })
def project_394(request): return render(request, 'pages/page_1.html', {'name': 'Project 394' })
def project_395(request): return render(request, 'pages/page_1.html', {'name': 'Project 395' })
def project_396(request): return render(request, 'pages/page_1.html', {'name': 'Project 396' })
def project_397(request): return render(request, 'pages/page_1.html', {'name': 'Project 397' })
def project_398(request): return render(request, 'pages/page_1.html', {'name': 'Project 398' })
def project_399(request): return render(request, 'pages/page_1.html', {'name': 'Project 399' })
