from django.views.generic import TemplateView
from django.shortcuts import render

# class page_4(TemplateView): template_name = 'pages/page_4.html'
def page_4(request): return render(request, 'pages/page_4.html', {'name': 'Page 4' })

def project_400(request): return render(request, 'pages/page_1.html', {'name': 'Project 400' })
def project_401(request): return render(request, 'pages/page_1.html', {'name': 'Project 401' })
def project_402(request): return render(request, 'pages/page_1.html', {'name': 'Project 402' })
def project_403(request): return render(request, 'pages/page_1.html', {'name': 'Project 403' })
def project_404(request): return render(request, 'pages/page_1.html', {'name': 'Project 404' })
def project_405(request): return render(request, 'pages/page_1.html', {'name': 'Project 405' })
def project_406(request): return render(request, 'pages/page_1.html', {'name': 'Project 406' })
def project_407(request): return render(request, 'pages/page_1.html', {'name': 'Project 407' })
def project_408(request): return render(request, 'pages/page_1.html', {'name': 'Project 408' })
def project_409(request): return render(request, 'pages/page_1.html', {'name': 'Project 409' })

def project_410(request): return render(request, 'pages/page_1.html', {'name': 'Project 410' })
def project_411(request): return render(request, 'pages/page_1.html', {'name': 'Project 411' })
def project_412(request): return render(request, 'pages/page_1.html', {'name': 'Project 412' })
def project_413(request): return render(request, 'pages/page_1.html', {'name': 'Project 413' })
def project_414(request): return render(request, 'pages/page_1.html', {'name': 'Project 414' })
def project_415(request): return render(request, 'pages/page_1.html', {'name': 'Project 415' })
def project_416(request): return render(request, 'pages/page_1.html', {'name': 'Project 416' })
def project_417(request): return render(request, 'pages/page_1.html', {'name': 'Project 417' })
def project_418(request): return render(request, 'pages/page_1.html', {'name': 'Project 418' })
def project_419(request): return render(request, 'pages/page_1.html', {'name': 'Project 419' })

def project_420(request): return render(request, 'pages/page_1.html', {'name': 'Project 420' })
def project_421(request): return render(request, 'pages/page_1.html', {'name': 'Project 421' })
def project_422(request): return render(request, 'pages/page_1.html', {'name': 'Project 422' })
def project_423(request): return render(request, 'pages/page_1.html', {'name': 'Project 423' })
def project_424(request): return render(request, 'pages/page_1.html', {'name': 'Project 424' })
def project_425(request): return render(request, 'pages/page_1.html', {'name': 'Project 425' })
def project_426(request): return render(request, 'pages/page_1.html', {'name': 'Project 426' })
def project_427(request): return render(request, 'pages/page_1.html', {'name': 'Project 427' })
def project_428(request): return render(request, 'pages/page_1.html', {'name': 'Project 428' })
def project_429(request): return render(request, 'pages/page_1.html', {'name': 'Project 429' })

def project_430(request): return render(request, 'pages/page_1.html', {'name': 'Project 430' })
def project_431(request): return render(request, 'pages/page_1.html', {'name': 'Project 431' })
def project_432(request): return render(request, 'pages/page_1.html', {'name': 'Project 432' })
def project_433(request): return render(request, 'pages/page_1.html', {'name': 'Project 433' })
def project_434(request): return render(request, 'pages/page_1.html', {'name': 'Project 434' })
def project_435(request): return render(request, 'pages/page_1.html', {'name': 'Project 435' })
def project_436(request): return render(request, 'pages/page_1.html', {'name': 'Project 436' })
def project_437(request): return render(request, 'pages/page_1.html', {'name': 'Project 437' })
def project_438(request): return render(request, 'pages/page_1.html', {'name': 'Project 438' })
def project_439(request): return render(request, 'pages/page_1.html', {'name': 'Project 439' })

def project_440(request): return render(request, 'pages/page_1.html', {'name': 'Project 440' })
def project_441(request): return render(request, 'pages/page_1.html', {'name': 'Project 441' })
def project_442(request): return render(request, 'pages/page_1.html', {'name': 'Project 442' })
def project_443(request): return render(request, 'pages/page_1.html', {'name': 'Project 443' })
def project_444(request): return render(request, 'pages/page_1.html', {'name': 'Project 444' })
def project_445(request): return render(request, 'pages/page_1.html', {'name': 'Project 445' })
def project_446(request): return render(request, 'pages/page_1.html', {'name': 'Project 446' })
def project_447(request): return render(request, 'pages/page_1.html', {'name': 'Project 447' })
def project_448(request): return render(request, 'pages/page_1.html', {'name': 'Project 448' })
def project_449(request): return render(request, 'pages/page_1.html', {'name': 'Project 449' })

def project_450(request): return render(request, 'pages/page_1.html', {'name': 'Project 450' })
def project_451(request): return render(request, 'pages/page_1.html', {'name': 'Project 451' })
def project_452(request): return render(request, 'pages/page_1.html', {'name': 'Project 452' })
def project_453(request): return render(request, 'pages/page_1.html', {'name': 'Project 453' })
def project_454(request): return render(request, 'pages/page_1.html', {'name': 'Project 454' })
def project_455(request): return render(request, 'pages/page_1.html', {'name': 'Project 455' })
def project_456(request): return render(request, 'pages/page_1.html', {'name': 'Project 456' })
def project_457(request): return render(request, 'pages/page_1.html', {'name': 'Project 457' })
def project_458(request): return render(request, 'pages/page_1.html', {'name': 'Project 458' })
def project_459(request): return render(request, 'pages/page_1.html', {'name': 'Project 459' })

def project_460(request): return render(request, 'pages/page_1.html', {'name': 'Project 460' })
def project_461(request): return render(request, 'pages/page_1.html', {'name': 'Project 461' })
def project_462(request): return render(request, 'pages/page_1.html', {'name': 'Project 462' })
def project_463(request): return render(request, 'pages/page_1.html', {'name': 'Project 463' })
def project_464(request): return render(request, 'pages/page_1.html', {'name': 'Project 464' })
def project_465(request): return render(request, 'pages/page_1.html', {'name': 'Project 465' })
def project_466(request): return render(request, 'pages/page_1.html', {'name': 'Project 466' })
def project_467(request): return render(request, 'pages/page_1.html', {'name': 'Project 467' })
def project_468(request): return render(request, 'pages/page_1.html', {'name': 'Project 468' })
def project_469(request): return render(request, 'pages/page_1.html', {'name': 'Project 469' })

def project_470(request): return render(request, 'pages/page_1.html', {'name': 'Project 470' })
def project_471(request): return render(request, 'pages/page_1.html', {'name': 'Project 471' })
def project_472(request): return render(request, 'pages/page_1.html', {'name': 'Project 472' })
def project_473(request): return render(request, 'pages/page_1.html', {'name': 'Project 473' })
def project_474(request): return render(request, 'pages/page_1.html', {'name': 'Project 474' })
def project_475(request): return render(request, 'pages/page_1.html', {'name': 'Project 475' })
def project_476(request): return render(request, 'pages/page_1.html', {'name': 'Project 476' })
def project_477(request): return render(request, 'pages/page_1.html', {'name': 'Project 477' })
def project_478(request): return render(request, 'pages/page_1.html', {'name': 'Project 478' })
def project_479(request): return render(request, 'pages/page_1.html', {'name': 'Project 479' })

def project_480(request): return render(request, 'pages/page_1.html', {'name': 'Project 480' })
def project_481(request): return render(request, 'pages/page_1.html', {'name': 'Project 481' })
def project_482(request): return render(request, 'pages/page_1.html', {'name': 'Project 482' })
def project_483(request): return render(request, 'pages/page_1.html', {'name': 'Project 483' })
def project_484(request): return render(request, 'pages/page_1.html', {'name': 'Project 484' })
def project_485(request): return render(request, 'pages/page_1.html', {'name': 'Project 485' })
def project_486(request): return render(request, 'pages/page_1.html', {'name': 'Project 486' })
def project_487(request): return render(request, 'pages/page_1.html', {'name': 'Project 487' })
def project_488(request): return render(request, 'pages/page_1.html', {'name': 'Project 488' })
def project_489(request): return render(request, 'pages/page_1.html', {'name': 'Project 489' })

def project_490(request): return render(request, 'pages/page_1.html', {'name': 'Project 490' })
def project_491(request): return render(request, 'pages/page_1.html', {'name': 'Project 491' })
def project_492(request): return render(request, 'pages/page_1.html', {'name': 'Project 492' })
def project_493(request): return render(request, 'pages/page_1.html', {'name': 'Project 493' })
def project_494(request): return render(request, 'pages/page_1.html', {'name': 'Project 494' })
def project_495(request): return render(request, 'pages/page_1.html', {'name': 'Project 495' })
def project_496(request): return render(request, 'pages/page_1.html', {'name': 'Project 496' })
def project_497(request): return render(request, 'pages/page_1.html', {'name': 'Project 497' })
def project_498(request): return render(request, 'pages/page_1.html', {'name': 'Project 498' })
def project_499(request): return render(request, 'pages/page_1.html', {'name': 'Project 499' })
